### ISSUE TITLE
In Cluedin-server, Logs are coming with terminal color code, how can we disable them?

### ISSUE THREAD

**Issue by nitinerding** [CluedIn-io/Home#17]
Hi Team, 
As per our observability plan we have to send all the logs to our ELK stack. But challenge is that Cluedin logs are coming with many terminal color codes. It would be helpful if someone can suggest how can we disable them?

 `[38;5;0242m[[0m[38;5;0246m05:10:43[0m[38;5;0242m [0m[38;5;0197m[48;5;0238mERR[0m[38;5;0242m][[0m[38;5;0246mCluedIn.Core.Agent.Jobs.AgentJobProcessorState[0m[38;5;0242m] [0m[38;5;0253mCould not produce clue for [0m[38;5;0216mCluedIn.Crawling.ANA.Core.Models.Landscape.AddOnModel[0m
[38;5;0253mSystem.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'value')
[0m[38;5;0246m   at CluedIn.Crawling.Factories.ClueFactory.Create(EntityType type, String value, Guid accountId) in D:\a\1\s\Code\Crawling\-ToCleanup-\Factories\ClueFactory.cs:line 281
[0m[38;5;0246m   at CluedIn.Crawling.ANA.ClueProducers.Landscape.AddOnClueProducer.MakeClueImpl(AddOnModel input, Guid accountId)
[0m[38;5;0246m   at CluedIn.Crawling.CrawlerRunner`1.<>c__DisplayClass8_0.<SetupSubscriptions>b__0(Object o) in D:\a\1\s\Code\Crawling\-ToCleanup-\CrawlerRunner.cs:line 150`

We have deployed cluedin via helm chart on AKS.

Looking forward for your support.

Thanks,
Nitin Rana
nitin.rana@sap.com

**Comment by nitinerding** [comment]
Any suggestion on this topic please.
